"""'add avatar_url to people and identities'

Revision ID: 0cc7f6f1d8e7
Revises: 240b33d89d11
Create Date: 2026-07-18 14:36:34.623420
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0cc7f6f1d8e7"
down_revision: str | None = "240b33d89d11"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.add_column(sa.Column("avatar_url", sa.String(), nullable=True))

    with op.batch_alter_table("person_identities", schema=None) as batch_op:
        batch_op.add_column(sa.Column("avatar_url", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("person_identities", schema=None) as batch_op:
        batch_op.drop_column("avatar_url")

    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.drop_column("avatar_url")

    # ### end Alembic commands ###
