"""sync log counts items and proposals, not tasks

Revision ID: 193cd0d4b9c2
Revises: 8d4d780cccf4
Create Date: 2026-07-17 12:05:35.474197
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "193cd0d4b9c2"
down_revision: str | None = "8d4d780cccf4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sync_log", schema=None) as batch_op:
        batch_op.add_column(sa.Column("items_added", sa.Integer(), server_default="0", nullable=False))
        batch_op.add_column(sa.Column("items_updated", sa.Integer(), server_default="0", nullable=False))
        batch_op.add_column(sa.Column("proposals", sa.Integer(), server_default="0", nullable=False))
        batch_op.drop_column("tasks_added")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sync_log", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tasks_added", sa.INTEGER(), server_default="0", nullable=False))
        batch_op.drop_column("proposals")
        batch_op.drop_column("items_updated")
        batch_op.drop_column("items_added")

    # ### end Alembic commands ###
