"""initial schema

Revision ID: 4b439facfecf
Revises:
Create Date: 2026-07-16 15:05:23.373910
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "4b439facfecf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_config",
        sa.Column("namespace", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("namespace", "key"),
    )
    op.create_table(
        "buckets",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "link_overrides",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mention_id", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mention_id", "task_id", name="uq_link_override_pair"),
    )
    op.create_table(
        "mentions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("triaged", sa.Boolean(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mentions", schema=None) as batch_op:
        batch_op.create_index("ix_mentions_occurred_at", ["occurred_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mentions_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_mentions_triaged"), ["triaged"], unique=False)

    op.create_table(
        "sync_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("mentions_fetched", sa.Integer(), nullable=False),
        sa.Column("tasks_added", sa.Integer(), nullable=False),
        sa.Column("tasks_updated", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sync_log", schema=None) as batch_op:
        batch_op.create_index("ix_sync_log_started_at", ["started_at"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("bucket", sa.String(), nullable=False),
        sa.Column("bucket_override", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("unread", sa.Boolean(), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("title_override", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "synced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index("ix_tasks_bucket", ["bucket"], unique=False)

    op.create_table(
        "task_mentions",
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("mention_id", sa.String(), nullable=False),
        sa.Column("linked_by", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["mention_id"], ["mentions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "mention_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_mentions")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_tasks_bucket")

    op.drop_table("tasks")
    with op.batch_alter_table("sync_log", schema=None) as batch_op:
        batch_op.drop_index("ix_sync_log_started_at")

    op.drop_table("sync_log")
    with op.batch_alter_table("mentions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mentions_triaged"))
        batch_op.drop_index(batch_op.f("ix_mentions_source"))
        batch_op.drop_index("ix_mentions_occurred_at")

    op.drop_table("mentions")
    op.drop_table("link_overrides")
    op.drop_table("buckets")
    op.drop_table("app_config")
    # ### end Alembic commands ###
