"""add priority to tasks

Revision ID: 53f580e644d9
Revises: c00afde4c3f1
Create Date: 2026-07-17 23:45:00.897074
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "53f580e644d9"
down_revision: str | None = "c00afde4c3f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("priority", sa.Integer(), server_default="50", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("priority")

    # ### end Alembic commands ###
