"""sources you add, and which one fetched each item

Revision ID: 8d4d780cccf4
Revises: 3d3a0b20744a
Create Date: 2026-07-16 16:53:45.589023
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8d4d780cccf4"
down_revision: str | None = "3d3a0b20744a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_instances",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("source_instances", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_instances_kind"), ["kind"], unique=False)

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("instance_id", sa.String(), nullable=True))
        batch_op.create_index(batch_op.f("ix_items_instance_id"), ["instance_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_items_instance_id"))
        batch_op.drop_column("instance_id")

    with op.batch_alter_table("source_instances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_instances_kind"))

    op.drop_table("source_instances")
    # ### end Alembic commands ###
