"""triage rules and item triage reason

Revision ID: 9a33f12272f9
Revises: 1e06e9e03bd0
Create Date: 2026-07-17 17:48:24.070027
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9a33f12272f9"
down_revision: str | None = "1e06e9e03bd0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "triage_rules",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("condition", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("triage_reason", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("triaged_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("triaged_at")
        batch_op.drop_column("triage_reason")

    op.drop_table("triage_rules")
    # ### end Alembic commands ###
