"""add archived_at to buckets

Revision ID: c00afde4c3f1
Revises: 409d676b0983
Create Date: 2026-07-17 17:03:44.579585
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c00afde4c3f1"
down_revision: str | None = "409d676b0983"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("buckets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("buckets", schema=None) as batch_op:
        batch_op.drop_column("archived_at")

    # ### end Alembic commands ###
